# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1488, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.tabWidget.setObjectName("tabWidget")
        self.Area = QtWidgets.QWidget()
        self.Area.setObjectName("Area")
        self.lineEdit = QtWidgets.QLineEdit(self.Area)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 360, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.Area_Title = QtWidgets.QLabel(self.Area)
        self.Area_Title.setGeometry(QtCore.QRect(10, 10, 461, 30))
        self.Area_Title.setStyleSheet("font: 75 24pt \"Arial\";")
        self.Area_Title.setObjectName("Area_Title")
        self.tabWidget.addTab(self.Area, "")
        self.Length = QtWidgets.QWidget()
        self.Length.setObjectName("Length")
        self.tabWidget.addTab(self.Length, "")
        self.Mass = QtWidgets.QWidget()
        self.Mass.setObjectName("Mass")
        self.tabWidget.addTab(self.Mass, "")
        self.Speed = QtWidgets.QWidget()
        self.Speed.setObjectName("Speed")
        self.tabWidget.addTab(self.Speed, "")
        self.Time = QtWidgets.QWidget()
        self.Time.setObjectName("Time")
        self.tabWidget.addTab(self.Time, "")
        self.Temperature = QtWidgets.QWidget()
        self.Temperature.setObjectName("Temperature")
        self.tabWidget.addTab(self.Temperature, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1488, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Area_Title.setText(_translate("MainWindow", "Convert Area / 面积换算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Area), _translate("MainWindow", "Area"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Length), _translate("MainWindow", "Length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Mass), _translate("MainWindow", "Mass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Speed), _translate("MainWindow", "Speed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Time), _translate("MainWindow", "Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Temperature), _translate("MainWindow", "Temperature"))
